slash:
    path: /job_seekers_app
    controller: App\Controller\ApplicationController::slash

home:
    path: /job_seekers_app/home
    controller: App\Controller\ApplicationController::home

address_index:
    path: /job_seekers_app/index/address
    controller: App\Controller\AddressController::index

application_index:
    path: /job_seekers_app/index/application
    controller: App\Controller\ApplicationController::index

application_new:
    path: /job_seekers_app/new/application
    controller: App\Controller\ApplicationController::new

answer_new:
    path: /job_seekers_app/new/answer
    controller: App\Controller\AnswerController::new

answer_index:
    path: /job_seekers_app/index/answer
    controller: App\Controller\AnswerController::index

company_index:
    path: /job_seekers_app/index/company
    controller: App\Controller\CompanyController::index

company_new:
    path: /job_seekers_app/new/company
    controller: App\Controller\CompanyController::new

contact_index:
    path: /job_seekers_app/index/contact
    controller: App\Controller\ContactController::index

contact_new:
    path: /job_seekers_app/new/contact
    controller: App\Controller\ContactController::new

exchange_new:
    path: /job_seekers_app/exchange/new
    controller: App\Controller\ExchangeController::new

job_interview_new:
    path: /job_seekers_app/new/job_interview
    controller: App\Controller\JobInterviewController::new

project_presentation_index:
    path: /job_seekers_app/project/presentation
    controller: App\Controller\ProjectPresentationController::index

project_presentation_toc:
    path: /job_seekers_app/project/presentation/tableOfContent
    controller: App\Controller\ProjectPresentationController::tableOfContent

project_presentation_Objectifs:
    path: /job_seekers_app/project/presentation/objectifs
    controller: App\Controller\ProjectPresentationController::objectifsOfTheProject

project_presentation_needs:
    path: /job_seekers_app/project/presentation/needs
    controller: App\Controller\ProjectPresentationController::needs

project_presentation_answerTQ001:
    path: /job_seekers_app/project/presentation/answerTQ001
    controller: App\Controller\ProjectPresentationController::answerTQ001
project_presentation_answerTQ002:
    path: /job_seekers_app/project/presentation/answerTQ002
    controller: App\Controller\ProjectPresentationController::answerTQ002
project_presentation_answerTQ003:
    path: /job_seekers_app/project/presentation/answerTQ003
    controller: App\Controller\ProjectPresentationController::answerTQ003
project_presentation_answerTQ004:
    path: /job_seekers_app/project/presentation/answerTQ004
    controller: App\Controller\ProjectPresentationController::answerTQ004

project_presentation_technology:
    path: /job_seekers_app/project/presentation/technology
    controller: App\Controller\ProjectPresentationController::technology

user_new:
    path: /job_seekers_app/new/acount
    controller: App\Controller\UserController::new