index:
    path: /
    controller: App\Controller\ApplicationController::index

home:
    path: /home
    controller: App\Controller\ApplicationController::home

application:
    path: /application
    controller: App\Controller\ApplicationController::index
