index:
    path: /
    controller: App\Controller\ApplicationController::index

home:
    path: /home
    controller: App\Controller\ApplicationController::home

application:
    path: /application
    controller: App\Controller\ApplicationController::index

answer_new:
    path: /new/answer
    controller: App\Controller\AnswerController::new

job_interview_new:
    path: /new/job_interview
    controller: App\Controller\JobInterviewController::new
